# Generated by Django 5.1.4 on 2024-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Shop'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
