# Generated by Django 5.1.4 on 2024-12-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
