# Generated by Django 5.1.4 on 2024-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_emailconfirmation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Компания пользователя', max_length=255, null=True, verbose_name='Компания'),
        ),
    ]
