# Generated by Django 5.1.4 on 2024-12-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shops',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=1, help_text='Модель продукта', max_length=255, verbose_name='Модель продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Название продукта', max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=2, help_text='Компания пользователя', max_length=255, verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
