# Generated by Django 5.1.4 on 2024-12-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_category_shops_remove_shop_url_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Цена продукта в рублях', verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
