# Generated by Django 5.1.4 on 2024-12-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prce_rrc',
            field=models.PositiveIntegerField(default=0, help_text='Розничная цена продукта в рублях', verbose_name='Цена розничная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Количество продукта', verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
