# Generated by Django 5.1.4 on 2024-12-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_product_prce_rrc_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prce_rrc',
            new_name='price_rrc',
        ),
    ]
