# Generated by Django 5.1.4 on 2024-12-25 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_prce_rrc_product_price_rrc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_rrc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(help_text='Магазины, в которых представлена данная категория', related_name='categories', to='backend.shop', verbose_name='Магазины'),
        ),
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(default=0, help_text='Адрес магазина в интернете', verbose_name='URL магазина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Уникальное название продукта', max_length=255, unique=True, verbose_name='Название продукта'),
        ),
    ]
