# Generated by Django 5.1.4 on 2024-12-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='backend.shop'),
            preserve_default=False,
        ),
    ]
